download-external-modules: False
evaluate-variables: true
directory:
- ./
framework:
- terraform
skip-check:
- CKV2_GCP*
- CKV_AZURE*
- CKV2_AZURE*
- CKV_AWS_317 #Documentation is incorrect
- CKV2_AWS_52
- CKV2_AWS_5
- CKV2_AWS_67
- CKV2_AWS_12
- CKV_TF_1 # default to Terraform registry instead of Git
summary-position: bottom
output: 'cli'
compact: True
quiet: True